# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(849, 625)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gfunc_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.gfunc_group_box.setGeometry(QtCore.QRect(470, 180, 371, 201))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.gfunc_group_box.setFont(font)
        self.gfunc_group_box.setObjectName("gfunc_group_box")
        self.g_function_table_view = QtWidgets.QTableView(self.gfunc_group_box)
        self.g_function_table_view.setGeometry(QtCore.QRect(10, 20, 351, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_function_table_view.sizePolicy().hasHeightForWidth())
        self.g_function_table_view.setSizePolicy(sizePolicy)
        self.g_function_table_view.setSizeIncrement(QtCore.QSize(0, 0))
        self.g_function_table_view.setBaseSize(QtCore.QSize(2, 2))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.g_function_table_view.setFont(font)
        self.g_function_table_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.g_function_table_view.setLineWidth(5)
        self.g_function_table_view.setMidLineWidth(5)
        self.g_function_table_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.g_function_table_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.g_function_table_view.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.g_function_table_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.g_function_table_view.setProperty("showDropIndicator", False)
        self.g_function_table_view.setDragDropOverwriteMode(False)
        self.g_function_table_view.setShowGrid(True)
        self.g_function_table_view.setObjectName("g_function_table_view")
        self.g_function_table_view.horizontalHeader().setVisible(False)
        self.g_function_table_view.horizontalHeader().setCascadingSectionResizes(False)
        self.layoutWidget_2 = QtWidgets.QWidget(self.gfunc_group_box)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 120, 351, 73))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.g_function_grid_layout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.g_function_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.g_function_grid_layout.setObjectName("g_function_grid_layout")
        self.g_add_y_line_edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.g_add_y_line_edit.setBaseSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.g_add_y_line_edit.setFont(font)
        self.g_add_y_line_edit.setText("")
        self.g_add_y_line_edit.setObjectName("g_add_y_line_edit")
        self.g_function_grid_layout.addWidget(self.g_add_y_line_edit, 2, 0, 1, 1)
        self.g_add_point_label = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        self.g_add_point_label.setFont(font)
        self.g_add_point_label.setObjectName("g_add_point_label")
        self.g_function_grid_layout.addWidget(self.g_add_point_label, 0, 0, 1, 1)
        self.g_add_point_button = QtWidgets.QPushButton(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        self.g_add_point_button.setFont(font)
        self.g_add_point_button.setObjectName("g_add_point_button")
        self.g_function_grid_layout.addWidget(self.g_add_point_button, 2, 1, 1, 1)
        self.g_add_x_line_edit = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.g_add_x_line_edit.setBaseSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.g_add_x_line_edit.setFont(font)
        self.g_add_x_line_edit.setText("")
        self.g_add_x_line_edit.setObjectName("g_add_x_line_edit")
        self.g_function_grid_layout.addWidget(self.g_add_x_line_edit, 1, 0, 1, 1)
        self.bounds_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.bounds_group_box.setGeometry(QtCore.QRect(470, 380, 371, 111))
        self.bounds_group_box.setSizeIncrement(QtCore.QSize(2, 2))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        self.bounds_group_box.setFont(font)
        self.bounds_group_box.setObjectName("bounds_group_box")
        self.layoutWidget_4 = QtWidgets.QWidget(self.bounds_group_box)
        self.layoutWidget_4.setGeometry(QtCore.QRect(7, 20, 351, 79))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.bounds_grid_layout = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.bounds_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.bounds_grid_layout.setObjectName("bounds_grid_layout")
        self.from_label = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        self.from_label.setFont(font)
        self.from_label.setObjectName("from_label")
        self.bounds_grid_layout.addWidget(self.from_label, 1, 0, 1, 1)
        self.from_line_edit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.from_line_edit.setText("")
        self.from_line_edit.setObjectName("from_line_edit")
        self.bounds_grid_layout.addWidget(self.from_line_edit, 1, 1, 1, 1)
        self.to_line_edit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.to_line_edit.setText("")
        self.to_line_edit.setObjectName("to_line_edit")
        self.bounds_grid_layout.addWidget(self.to_line_edit, 2, 1, 1, 1)
        self.to_label = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        self.to_label.setFont(font)
        self.to_label.setObjectName("to_label")
        self.bounds_grid_layout.addWidget(self.to_label, 2, 0, 1, 1)
        self.add_bounds_button = QtWidgets.QPushButton(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        self.add_bounds_button.setFont(font)
        self.add_bounds_button.setObjectName("add_bounds_button")
        self.bounds_grid_layout.addWidget(self.add_bounds_button, 2, 2, 1, 1)
        self.enter_bounds_label = QtWidgets.QLabel(self.layoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.enter_bounds_label.setFont(font)
        self.enter_bounds_label.setObjectName("enter_bounds_label")
        self.bounds_grid_layout.addWidget(self.enter_bounds_label, 0, 0, 1, 2)
        self.build_button = QtWidgets.QPushButton(self.centralwidget)
        self.build_button.setGeometry(QtCore.QRect(760, 560, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        self.build_button.setFont(font)
        self.build_button.setObjectName("build_button")
        self.ffun_group_box = QtWidgets.QGroupBox(self.centralwidget)
        self.ffun_group_box.setGeometry(QtCore.QRect(470, 10, 371, 171))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.ffun_group_box.setFont(font)
        self.ffun_group_box.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.ffun_group_box.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.ffun_group_box.setAcceptDrops(False)
        self.ffun_group_box.setToolTipDuration(-1)
        self.ffun_group_box.setAutoFillBackground(True)
        self.ffun_group_box.setFlat(False)
        self.ffun_group_box.setCheckable(False)
        self.ffun_group_box.setObjectName("ffun_group_box")
        self.f_function_table_view = QtWidgets.QTableView(self.ffun_group_box)
        self.f_function_table_view.setGeometry(QtCore.QRect(10, 20, 351, 78))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_function_table_view.sizePolicy().hasHeightForWidth())
        self.f_function_table_view.setSizePolicy(sizePolicy)
        self.f_function_table_view.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.f_function_table_view.setFont(font)
        self.f_function_table_view.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.f_function_table_view.setLineWidth(5)
        self.f_function_table_view.setMidLineWidth(5)
        self.f_function_table_view.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.f_function_table_view.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.f_function_table_view.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.f_function_table_view.setAutoScrollMargin(0)
        self.f_function_table_view.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.f_function_table_view.setProperty("showDropIndicator", False)
        self.f_function_table_view.setDragDropOverwriteMode(False)
        self.f_function_table_view.setIconSize(QtCore.QSize(2, 2))
        self.f_function_table_view.setShowGrid(True)
        self.f_function_table_view.setObjectName("f_function_table_view")
        self.f_function_table_view.horizontalHeader().setVisible(False)
        self.f_function_table_view.horizontalHeader().setCascadingSectionResizes(False)
        self.layoutWidget = QtWidgets.QWidget(self.ffun_group_box)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 110, 351, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.f_function_grid_layout = QtWidgets.QGridLayout(self.layoutWidget)
        self.f_function_grid_layout.setContentsMargins(0, 0, 0, 0)
        self.f_function_grid_layout.setObjectName("f_function_grid_layout")
        self.f_add_coef_line_edit = QtWidgets.QLineEdit(self.layoutWidget)
        self.f_add_coef_line_edit.setBaseSize(QtCore.QSize(0, 32))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.f_add_coef_line_edit.setFont(font)
        self.f_add_coef_line_edit.setText("")
        self.f_add_coef_line_edit.setObjectName("f_add_coef_line_edit")
        self.f_function_grid_layout.addWidget(self.f_add_coef_line_edit, 1, 0, 1, 1)
        self.f_add_coef_label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        self.f_add_coef_label.setFont(font)
        self.f_add_coef_label.setObjectName("f_add_coef_label")
        self.f_function_grid_layout.addWidget(self.f_add_coef_label, 0, 0, 1, 1)
        self.f_add_coef_button = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        self.f_add_coef_button.setFont(font)
        self.f_add_coef_button.setObjectName("f_add_coef_button")
        self.f_function_grid_layout.addWidget(self.f_add_coef_button, 1, 1, 1, 1)
        self.roots_text_edit = QtWidgets.QTextEdit(self.centralwidget)
        self.roots_text_edit.setGeometry(QtCore.QRect(10, 500, 821, 51))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        self.roots_text_edit.setFont(font)
        self.roots_text_edit.setReadOnly(True)
        self.roots_text_edit.setObjectName("roots_text_edit")
        self.prompt_line_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.prompt_line_edit.setGeometry(QtCore.QRect(10, 10, 451, 471))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prompt_line_edit.sizePolicy().hasHeightForWidth())
        self.prompt_line_edit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        self.prompt_line_edit.setFont(font)
        self.prompt_line_edit.setAlignment(QtCore.Qt.AlignCenter)
        self.prompt_line_edit.setObjectName("prompt_line_edit")
        self.clear_graph_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_graph_button.setGeometry(QtCore.QRect(10, 560, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        self.clear_graph_button.setFont(font)
        self.clear_graph_button.setObjectName("clear_graph_button")
        self.choose_file_button = QtWidgets.QPushButton(self.centralwidget)
        self.choose_file_button.setGeometry(QtCore.QRect(400, 560, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Rubik")
        font.setPointSize(9)
        self.choose_file_button.setFont(font)
        self.choose_file_button.setObjectName("choose_file_button")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 30, 431, 431))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.graphical_layout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.graphical_layout.setContentsMargins(0, 0, 0, 0)
        self.graphical_layout.setObjectName("graphical_layout")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionGenerate_report = QtWidgets.QAction(MainWindow)
        self.actionGenerate_report.setObjectName("actionGenerate_report")
        self.actionClear = QtWidgets.QAction(MainWindow)
        self.actionClear.setObjectName("actionClear")
        self.actionBuild = QtWidgets.QAction(MainWindow)
        self.actionBuild.setObjectName("actionBuild")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionGenerate_report)
        self.menuFile.addAction(self.actionClose)
        self.menuEdit.addAction(self.actionBuild)
        self.menuEdit.addAction(self.actionClear)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.actionClose.triggered.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gfunc_group_box.setTitle(_translate("MainWindow", "G(x) data"))
        self.g_add_point_label.setText(_translate("MainWindow", "Add point"))
        self.g_add_point_button.setText(_translate("MainWindow", "Add"))
        self.bounds_group_box.setTitle(_translate("MainWindow", "Bounds"))
        self.from_label.setText(_translate("MainWindow", "From"))
        self.to_label.setText(_translate("MainWindow", "To"))
        self.add_bounds_button.setText(_translate("MainWindow", "Add"))
        self.enter_bounds_label.setText(_translate("MainWindow", "Enter bounds"))
        self.build_button.setText(_translate("MainWindow", "Build"))
        self.ffun_group_box.setTitle(_translate("MainWindow", "F(x) data"))
        self.f_add_coef_label.setText(_translate("MainWindow", "Add coefficient"))
        self.f_add_coef_button.setText(_translate("MainWindow", "Add"))
        self.prompt_line_edit.setText(_translate("MainWindow", "Enter the data or choose a file for building a graohical solution"))
        self.clear_graph_button.setText(_translate("MainWindow", "Clear"))
        self.choose_file_button.setText(_translate("MainWindow", "Choose file"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionGenerate_report.setText(_translate("MainWindow", "Generate report"))
        self.actionClear.setText(_translate("MainWindow", "Clear"))
        self.actionBuild.setText(_translate("MainWindow", "Build"))
        self.actionClose.setText(_translate("MainWindow", "Close"))

